# Generated by Django 5.2.5 on 2025-09-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('destination', models.TextField(max_length=200)),
                ('depature_date', models.DateField()),
                ('return_date', models.DateField()),
                ('Budget', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
