# Generated by Django 5.2.5 on 2025-09-06 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trips',
            name='Budget',
        ),
        migrations.AlterField(
            model_name='trips',
            name='destination',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trips',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/trip_images/'),
        ),
        migrations.AlterField(
            model_name='trips',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='trips',
            name='budget',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
